### ISSUE TITLE
Hypothesis Annotation plugin

### ISSUE THREAD

**Issue by ssheilah** [washingtonstateuniversity/opentext.wsu.edu#18]
We have a request to add the [Hypothesis Annotation plugin](https://pressbooks.com/blog/introducing-hypothesis-annotations-in-pressbooks/)

**Comment by jeremyfelt** [comment]
Hypothesis is now one of the plugins on opentext.wsu.edu https://github.com/washingtonstateuniversity/WSUWP-Build-Plugins-Open-Text 🎉
