### ISSUE TITLE
Download icons not appearing on book's homepage

### ISSUE THREAD

**Issue by ssheilah** [washingtonstateuniversity/opentext.wsu.edu#19]
[Other PressBooks instances](https://opentextbc.ca/accessibilitytoolkit/) have icons to download different versions of the book on the book's homepage. We can't find any functionality in the dashboard that will cause these to appear on books at opentext.wsu.edu.

**Comment by jeremyfelt** [comment]
We'll definitely make this happen as part of the book home page branding/theme changes if I can't find another setting for it.

**Comment by jeremyfelt** [comment]
This has been enabled for all books on opentext.wsu.edu. I had no idea it would be this easy.
