### ISSUE TITLE
Add wider-page-width theme from BCcampus

### ISSUE THREAD

**Issue by ssheilah** [washingtonstateuniversity/opentext.wsu.edu#24]
Per requests from faculty, in our recent meeting we discussed creating a theme that used a wider page width then thought perhaps we could instead use the theme from BCcampus -- I think it's [the one used in this book](https://opentextbc.ca/pressbooks/front-matter/open-creation-in-progress/).

**Comment by jeremyfelt** [comment]
The default theme provided on opentext.wsu.edu now has a wider page width. :tada:
